### ISSUE TITLE
No such file or directory: 'README.md' in new version 0.5.2

### ISSUE THREAD

**Issue by fletchowns** [edwardgeorge/virtualenv-clone#53]
Seems to be some sort of packaging issue with the new virtualenv-clone-0.5.2.tar.gz that is on PyPi currently.

My python version:
```
$ python --version
Python 3.4.9
```

Steps to reproduce:
```
$ python3 -m venv /tmp/myvenv
$ source /tmp/myvenv/bin/activate
(my-venv) $ wget https://files.pythonhosted.org/packages/9c/79/c5250612d1ef85d0051ebcc50ac57ef222767db938f1151fc2c904c7fcc6/virtualenv-clone-0.5.2.tar.gz
(my-venv) $ python3 -m pip install ./virtualenv-clone-0.5.2.tar.gz 
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Processing ./virtualenv-clone-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-brnab2gf/setup.py", line 9, in <module>
        with open('README.md') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-brnab2gf/
```

I didn't hit this directly, I ran into it by way of `./virtualenv-burrito.sh`

**Comment by eeshangarg** [comment]
@fletchowns: Thanks a lot for reporting, I just fixed this in #54! :)

**Comment by fletchowns** [comment]
Thank you @eeshangarg ! Much appreciated. Any word on when it will be deployed to PyPi?

**Comment by eeshangarg** [comment]
@fletchowns: Just made a new PyPI release. :)

**Comment by fletchowns** [comment]
Works for me now, thanks again @eeshangarg !
