### ISSUE TITLE
filenotfounderror : [Errno 2] No such file or directory /bin/python

### ISSUE THREAD

**Issue by randywreed** [edwardgeorge/virtualenv-clone#68]
Ubuntu 20.04
installed virtualenv-clone in the virtual environment 
command: virtualenv-clone ~/Rasa/rasa_kritik_check/ ~/Rasa/playground_rasa_kritik 

traceback:

```
~/Rasa/rasa_kritik_check$ virtualenv-clone ~/Rasa/rasa_kritik_check/ ~/Rasa/playground_rasa_kritik
Traceback (most recent call last):
  File "/home/randy/Rasa/rasa_kritik_check/rasa_kritik_check/bin/virtualenv-clone", line 8, in <module>
    sys.exit(main())
  File "/home/randy/Rasa/rasa_kritik_check/rasa_kritik_check/lib/python3.7/site-packages/clonevirtualenv.py", line 311, in main
    clone_virtualenv(old_dir, new_dir)
  File "/home/randy/Rasa/rasa_kritik_check/rasa_kritik_check/lib/python3.7/site-packages/clonevirtualenv.py", line 77, in clone_virtualenv
    version, sys_path = _virtualenv_sys(dst_dir)
  File "/home/randy/Rasa/rasa_kritik_check/rasa_kritik_check/lib/python3.7/site-packages/clonevirtualenv.py", line 60, in _virtualenv_sys
    stdout=subprocess.PIPE)
  File "/home/randy/.pyenv/versions/3.7.3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/randy/.pyenv/versions/3.7.3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/randy/Rasa/playground_rasa_kritik/bin/python': '/home/randy/Rasa/playground_rasa_kritik/bin/python'
```
In this case /bin/python is a symbolic link 
```
lrwxrwxrwx 1 randy randy   44 Feb 21 23:22 python -> /home/randy/.pyenv/versions/3.7.3/bin/python
lrwxrwxrwx 1 randy randy    6 Feb 21 23:22 python3 -> python
```

**Comment by timabbott** [comment]
Thanks for the report!  I don't have time to investigate right now, but it sounds like a missing `readlink` somewhere, if you want to debug and submit a PR.
